/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.andevs.taller.mvc.view.employee;

import com.andevs.taller.mvc.controller.EmployeeController;
import com.andevs.taller.mvc.controller.LogController;
import lombok.Data;
import lombok.EqualsAndHashCode;

@EqualsAndHashCode(callSuper = true)
@Data
public class EmployeeView extends javax.swing.JFrame {

    public EmployeeView() {
        initComponents();
    }

    public void addController(EmployeeController employeeController) {
        getCreateButton().addActionListener(employeeController);
        getUpdateButton().addActionListener(employeeController);
        getDeleteButton().addActionListener(employeeController);
        getReadAllButton().addActionListener(employeeController);
        getReadButton().addActionListener(employeeController);
        getExitButton().addActionListener(employeeController);
        getCleanButton().addActionListener(employeeController);
        getErrorsLogs().addActionListener(employeeController);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new org.edisoncor.gui.panel.PanelImage();
        lastModifiedLabel = new javax.swing.JLabel();
        surnameField = new javax.swing.JTextField();
        createdOnLabel = new javax.swing.JLabel();
        surname2Field = new javax.swing.JTextField();
        lastModifiedField = new javax.swing.JLabel();
        createButton = new org.edisoncor.gui.button.ButtonIpod();
        cleanButton = new org.edisoncor.gui.button.ButtonIpod();
        updateButton = new org.edisoncor.gui.button.ButtonIpod();
        deleteButton = new org.edisoncor.gui.button.ButtonIpod();
        docNumberLabel = new javax.swing.JLabel();
        readButton = new org.edisoncor.gui.button.ButtonIpod();
        nameLabel = new javax.swing.JLabel();
        exitButton = new org.edisoncor.gui.button.ButtonIpod();
        surname2Label = new javax.swing.JLabel();
        readAllButton = new org.edisoncor.gui.button.ButtonIpod();
        surnameLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        docNumberField = new javax.swing.JTextField();
        createdOnField = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        errorsLogs = new org.edisoncor.gui.button.ButtonIcon();
        phoneLabel = new javax.swing.JLabel();
        cleanAfterCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N

        lastModifiedLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastModifiedLabel.setForeground(new java.awt.Color(255, 255, 255));
        lastModifiedLabel.setText("Actualizado :");

        surnameField.setBackground(new java.awt.Color(0, 0, 188));
        surnameField.setForeground(new java.awt.Color(255, 255, 255));
        surnameField.setCaretColor(new java.awt.Color(255, 255, 255));

        createdOnLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createdOnLabel.setForeground(new java.awt.Color(255, 255, 255));
        createdOnLabel.setText("Creado :");

        surname2Field.setBackground(new java.awt.Color(0, 0, 188));
        surname2Field.setForeground(new java.awt.Color(255, 255, 255));
        surname2Field.setCaretColor(new java.awt.Color(255, 255, 255));

        lastModifiedField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastModifiedField.setForeground(new java.awt.Color(255, 255, 255));

        createButton.setText("Grabar");
        createButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cleanButton.setText("Limpiar");
        cleanButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Actualizar");
        updateButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        deleteButton.setText("Eliminar");
        deleteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        docNumberLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        docNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        docNumberLabel.setText("Documento :");

        readButton.setText("Consultar");
        readButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("Nombre :");

        exitButton.setText("Salir");
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        surname2Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        surname2Label.setForeground(new java.awt.Color(255, 255, 255));
        surname2Label.setText("Segundo Apellido :");

        readAllButton.setText("Listar");
        readAllButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        readAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readAllButtonActionPerformed(evt);
            }
        });

        surnameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        surnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        surnameLabel.setText("Primer Apellido :");

        idLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 255, 255));

        docNumberField.setBackground(new java.awt.Color(0, 0, 188));
        docNumberField.setForeground(new java.awt.Color(255, 255, 255));
        docNumberField.setCaretColor(new java.awt.Color(255, 255, 255));

        createdOnField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createdOnField.setForeground(new java.awt.Color(255, 255, 255));

        nameField.setBackground(new java.awt.Color(0, 0, 188));
        nameField.setForeground(new java.awt.Color(255, 255, 255));
        nameField.setCaretColor(new java.awt.Color(255, 255, 255));

        phoneField.setBackground(new java.awt.Color(0, 0, 188));
        phoneField.setForeground(new java.awt.Color(255, 255, 255));
        phoneField.setCaretColor(new java.awt.Color(255, 255, 255));

        errorsLogs.setBackground(new java.awt.Color(0, 0, 188));
        errorsLogs.setForeground(new java.awt.Color(0, 0, 188));
        errorsLogs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log.png"))); // NOI18N

        phoneLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        phoneLabel.setText("Telefono :");

        cleanAfterCheckBox.setBackground(new java.awt.Color(0, 0, 188));
        cleanAfterCheckBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cleanAfterCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        cleanAfterCheckBox.setText("Limpiar despues de ejecutar");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
                backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(nameLabel)
                                                                        .addComponent(surnameLabel)
                                                                        .addComponent(surname2Label)
                                                                        .addComponent(docNumberLabel))
                                                                .addGap(27, 27, 27)
                                                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(surnameField)
                                                                        .addComponent(surname2Field)
                                                                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(docNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lastModifiedLabel)
                                                                        .addComponent(createdOnLabel)
                                                                        .addComponent(phoneLabel))
                                                                .addGap(68, 68, 68)
                                                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                                                .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                        .addComponent(createdOnField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(lastModifiedField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                .addGap(59, 59, 59))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(readButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(78, 78, 78))
                                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                                .addGap(38, 38, 38)
                                                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(readAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cleanButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                                .addGap(109, 109, 109)
                                                                .addComponent(cleanAfterCheckBox)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(errorsLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27))))
        );
        backgroundPanelLayout.setVerticalGroup(
                backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(docNumberLabel)
                                        .addComponent(docNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nameLabel)
                                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(surnameLabel)
                                        .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(surname2Label)
                                        .addComponent(surname2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(phoneLabel)
                                        .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(createdOnLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(createdOnField, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lastModifiedField, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastModifiedLabel))
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(backgroundPanelLayout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(readButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(readAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cleanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(11, 11, 11)
                                                .addComponent(cleanAfterCheckBox)
                                                .addGap(8, 8, 8))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(errorsLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanButtonActionPerformed

    private void readAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readAllButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readAllButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.PanelImage backgroundPanel;
    private javax.swing.JCheckBox cleanAfterCheckBox;
    private org.edisoncor.gui.button.ButtonIpod cleanButton;
    private org.edisoncor.gui.button.ButtonIpod createButton;
    private javax.swing.JLabel createdOnField;
    private javax.swing.JLabel createdOnLabel;
    private org.edisoncor.gui.button.ButtonIpod deleteButton;
    private javax.swing.JTextField docNumberField;
    private javax.swing.JLabel docNumberLabel;
    private org.edisoncor.gui.button.ButtonIcon errorsLogs;
    private org.edisoncor.gui.button.ButtonIpod exitButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel lastModifiedField;
    private javax.swing.JLabel lastModifiedLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private org.edisoncor.gui.button.ButtonIpod readAllButton;
    private org.edisoncor.gui.button.ButtonIpod readButton;
    private javax.swing.JTextField surname2Field;
    private javax.swing.JLabel surname2Label;
    private javax.swing.JTextField surnameField;
    private javax.swing.JLabel surnameLabel;
    private org.edisoncor.gui.button.ButtonIpod updateButton;
    // End of variables declaration//GEN-END:variables
}
